name: Update Version on Merge

on:
  push:
    branches:
      - master

jobs:
  version-bump:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Bump version and push tag
        run: |
          # Assuming the version file contains a simple number like 1.0.0
          VERSION=$(cat VERSION)
          NEW_VERSION=$(echo $VERSION | awk -F. '{$NF = $NF + 1;} 1' | sed 's/ /./g')
          echo $NEW_VERSION > VERSION
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add VERSION
          git commit -m "Bump version to $NEW_VERSION"
          git tag $NEW_VERSION
          git push origin main --tags
