name: Check WorkFlow

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - uses: jannekem/run-python-script-action@v1
        with:
          script: |
            print("hello")
            f = open("version.txt", "r")
            ver_number = 0
            for line in f.readlines():
                print(line)
                
                if "version" in line:
                    ver_number = line.split("=")[0]
                    break
            print(ver_number)
            ver_number = ver_number + 1
            f.close()
            f = open("version.txt", "w")
            f.write(f"VERSION={ver_number}")
            f.close()
            print(ver_number)
            
                
