name: Version Update

on:
  push:
    branches: [ main ]

jobs:
  updateversion:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3 # checkout the repository content to github runner.
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x #install the python needed      
      - name: execute py script
        run: |
             python version_update.py
             git config user.name github-actions
             git config user.email github-actions@github.com
             git add .
             git commit --amend
             git push

